// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhbbkN8fz1BRpAH9QlOfla97fFDl79uo',
    appId: '1:234598193617:web:a9de8ec2bddcce5c2c28f0',
    messagingSenderId: '234598193617',
    projectId: 'yasodha-app-backend',
    authDomain: 'yasodha-app-backend.firebaseapp.com',
    databaseURL: 'https://yasodha-app-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yasodha-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4OU2qn4PdE_JAddtAv-TSniTtYebdjo',
    appId: '1:234598193617:android:b45897b7d6e9709e2c28f0',
    messagingSenderId: '234598193617',
    projectId: 'yasodha-app-backend',
    databaseURL: 'https://yasodha-app-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yasodha-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDixqxYcKqCjmsoSUYiK4YbdmhYgDF5rOo',
    appId: '1:234598193617:ios:c166e1703419bf272c28f0',
    messagingSenderId: '234598193617',
    projectId: 'yasodha-app-backend',
    databaseURL: 'https://yasodha-app-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yasodha-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.yasoDistributor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDixqxYcKqCjmsoSUYiK4YbdmhYgDF5rOo',
    appId: '1:234598193617:ios:c166e1703419bf272c28f0',
    messagingSenderId: '234598193617',
    projectId: 'yasodha-app-backend',
    databaseURL: 'https://yasodha-app-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yasodha-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.yasoDistributor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDU6zbBt7wdRxYzkWe0s1h5F4lThYyKdc',
    appId: '1:234598193617:web:7a4e5cce5e008c3b2c28f0',
    messagingSenderId: '234598193617',
    projectId: 'yasodha-app-backend',
    authDomain: 'yasodha-app-backend.firebaseapp.com',
    databaseURL: 'https://yasodha-app-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yasodha-app-backend.firebasestorage.app',
  );
}
